name = "BCJCalibratinator"
uuid = "a89bb55e-884e-48c3-ba05-e3917bd289c9"
authors = ["Joby M. Anthony III", "Daniel S. Kenney"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
